/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nairn' at '29/7/21 3:53 PM' with Gradle 3.0
 *
 * @author nairn, @date 29/7/21 3:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
