/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nairn' at '1/8/21 9:16 PM' with Gradle 3.0
 *
 * @author nairn, @date 1/8/21 9:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
