/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nairn' at '28/7/21 3:44 PM' with Gradle 3.0
 *
 * @author nairn, @date 28/7/21 3:44 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
