/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nairn' at '4/8/21 9:37 AM' with Gradle 3.0
 *
 * @author nairn, @date 4/8/21 9:37 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
