/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nairn' at '2/8/21 4:41 PM' with Gradle 3.0
 *
 * @author nairn, @date 2/8/21 4:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
