/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nairn' at '30/7/21 7:43 PM' with Gradle 3.0
 *
 * @author nairn, @date 30/7/21 7:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
