/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nairn' at '31/7/21 3:22 PM' with Gradle 3.0
 *
 * @author nairn, @date 31/7/21 3:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
